# Generated by Django 3.2 on 2021-04-30 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='images',
            field=models.ImageField(default=datetime.datetime(2021, 4, 30, 12, 10, 23, 50221, tzinfo=utc), upload_to='media/'),
        ),
    ]
